In [91]:
import torch

In [92]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [93]:
t1.dtype

torch.float32

In [94]:
# vector
t2 =  torch.tensor([1.,2,3,5])
t2

tensor([1., 2., 3., 5.])

In [95]:
t2.dtype

torch.float32

In [96]:
# Matix
t3 = torch.tensor([[5.,6], [7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [97]:
t4 = torch.tensor([
    [[11,13,14], [24,66,77]],
    [[11,13,14], [24,66,77]]
])
t4

tensor([[[11, 13, 14],
         [24, 66, 77]],

        [[11, 13, 14],
         [24, 66, 77]]])

In [98]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


In [99]:
# Tensors operations and gradients
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [100]:
y = x*w+b
y

tensor(17., grad_fn=<AddBackward0>)

In [101]:
y.dtype

torch.float32

In [102]:
# Compute derivatives
y.backward()

In [103]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [104]:
# Interoperability with Numpy

import numpy as np
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [105]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [106]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [107]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [108]:
inputs = np.array([[67,77,85],[45,66,74],[36,75,86],[66,46,74]], dtype='float32')
inputs

array([[67., 77., 85.],
       [45., 66., 74.],
       [36., 75., 86.],
       [66., 46., 74.]], dtype=float32)

In [109]:
targets = np.array([[56, 70], [83, 101], [54,78], [56,75]], dtype='float32')
targets

array([[ 56.,  70.],
       [ 83., 101.],
       [ 54.,  78.],
       [ 56.,  75.]], dtype=float32)

In [110]:
# convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print("inputs: ",inputs)
print("targets: ",targets)

inputs:  tensor([[67., 77., 85.],
        [45., 66., 74.],
        [36., 75., 86.],
        [66., 46., 74.]])
targets:  tensor([[ 56.,  70.],
        [ 83., 101.],
        [ 54.,  78.],
        [ 56.,  75.]])


In [111]:
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.8740, -0.2212, -0.1348],
        [ 1.4098, -1.5266, -1.6186]], requires_grad=True)
tensor([ 0.7648, -1.0886], requires_grad=True)


In [112]:
print(w.grad)

None


In [113]:
w

tensor([[ 0.8740, -0.2212, -0.1348],
        [ 1.4098, -1.5266, -1.6186]], requires_grad=True)

In [114]:
inputs

tensor([[67., 77., 85.],
        [45., 66., 74.],
        [36., 75., 86.],
        [66., 46., 74.]])

In [115]:
w.t()

tensor([[ 0.8740,  1.4098],
        [-0.2212, -1.5266],
        [-0.1348, -1.6186]], grad_fn=<TBackward0>)

In [116]:
inputs @ w.t() + b

tensor([[  30.8235, -161.7573],
        [  15.5132, -158.1765],
        [   4.0383, -204.0271],
        [  38.2908,  -98.0392]], grad_fn=<AddBackward0>)

In [117]:
def model(inputs):
    return inputs @ w.t()+b

In [118]:
preds = model(inputs)
print(preds)

tensor([[  30.8235, -161.7573],
        [  15.5132, -158.1765],
        [   4.0383, -204.0271],
        [  38.2908,  -98.0392]], grad_fn=<AddBackward0>)


In [119]:
# compare to target
print(targets)

tensor([[ 56.,  70.],
        [ 83., 101.],
        [ 54.,  78.],
        [ 56.,  75.]])


In [120]:
difff = preds - targets
muilti = difff * difff
muilti

tensor([[  633.8580, 53711.4414],
        [ 4554.4683, 67172.4375],
        [ 2496.1670, 79539.2500],
        [  313.6141, 29942.5586]], grad_fn=<MulBackward0>)

In [121]:
torch.sum(muilti)

tensor(238363.7969, grad_fn=<SumBackward0>)

In [122]:
difff.numel()

8

In [123]:
torch.sum(muilti) / difff.numel()

tensor(29795.4746, grad_fn=<DivBackward0>)

In [124]:
# mse loss
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff * diff) / diff.numel()

In [125]:
loss = mse(preds, targets)
print(loss)

tensor(29795.4746, grad_fn=<DivBackward0>)


In [127]:
loss.backward()

In [128]:
# gradients for weights
print(w)
print(w.grad)

tensor([[ 0.8740, -0.2212, -0.1348],
        [ 1.4098, -1.5266, -1.6186]], requires_grad=True)
tensor([[ -1922.7894,  -2738.6167,  -3185.3022],
        [-12191.0596, -16015.6973, -18984.4121]])
