In [2]:
import torch

In [6]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [10]:
# vector
t2 =  torch.tensor([1.,2,3,5])
t2

tensor([1., 2., 3., 5.])

In [11]:
t2.dtype

torch.float32

In [12]:
# Matix
t3 = torch.tensor([[5.,6], [7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [14]:
t4 = torch.tensor([
    [[11,13,14], [24,66,77]],
    [[11,13,14], [24,66,77]]
])
t4

tensor([[[11, 13, 14],
         [24, 66, 77]],

        [[11, 13, 14],
         [24, 66, 77]]])

In [16]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


In [19]:
# Tensors operations and gradients
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [21]:
y = x*w*b
y

tensor(60., grad_fn=<MulBackward0>)

In [22]:
y.dtype

torch.float32

In [23]:
# Compute derivatives
y.backward()

In [24]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(15.)
dy/db: tensor(12.)


In [25]:
# Interoperability with Numpy

import numpy as np
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [27]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [28]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [29]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [31]:
inputs = np.array([[67,77,85],[45,66,74],[36,75,86],[66,46,74]], dtype='float32')
inputs

array([[67., 77., 85.],
       [45., 66., 74.],
       [36., 75., 86.],
       [66., 46., 74.]], dtype=float32)

In [32]:
targets = np.array([[56, 70], [83, 101], [54,78], [56,75]], dtype='float32')
targets

array([[ 56.,  70.],
       [ 83., 101.],
       [ 54.,  78.],
       [ 56.,  75.]], dtype=float32)

In [33]:
# convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[67., 77., 85.],
        [45., 66., 74.],
        [36., 75., 86.],
        [66., 46., 74.]])
tensor([[ 56.,  70.],
        [ 83., 101.],
        [ 54.,  78.],
        [ 56.,  75.]])
